apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: mysqls.otus.homework
spec:
  group: otus.homework
  scope: Namespaced
  names:
    kind: MySQL
    plural: mysqls
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required:
                - image
                - database
                - password
                - storage_size
              properties:
                image:
                  type: string
                  description: "Docker image for MySQL"
                  example: "mysql:5.7"
                database:
                  type: string
                  description: "Database name"
                  example: "mydb"
                password:
                  type: string
                  description: "Database password"
                  minLength: 1
                storage_size:
                  type: string
                  description: "Storage size (e.g., 1Gi, 10Gi)"
                  pattern: '^\d+(Mi|Gi|Ti)$'
            status:
              type: object
              properties:
                phase:
                  type: string
                  description: "Current phase (Pending, Running, Failed)"
