apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-operator
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-operator
  template:
    metadata:
      labels:
        app: mysql-operator
    spec:
      serviceAccountName: mysql-operator
      containers:
      - name: operator
        image: roflmaoinmysoul/mysql-operator:1.0.0
        imagePullPolicy: IfNotPresent
        env:
        - name: OPERATOR_NAME
          value: mysql-operator
        - name: WATCH_NAMESPACE
          value: ""
        ports:
        - containerPort: 8080
          name: metrics
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
