apiVersion: v1
kind: Pod
metadata:
  name: nginx-distroless
  labels:
    app: nginx-distroless
spec:
  containers:
  - name: nginx
    image: kyos0109/nginx-distroless
    ports:
    - containerPort: 80
      protocol: TCP
    resources:
      requests:
        memory: "64Mi"
        cpu: "100m"
      limits:
        memory: "128Mi"
        cpu: "200m"
