apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: homework-networks
  namespace: argocd
spec:
  project: otus
  source:
    repoURL: https://github.com/Kuber-2025-08OTUS/SimonKonstantinov_repo.git
    targetRevision: kubernetes-networks
    path: kubernetes-networks
  destination:
    server: https://kubernetes.default.svc
    namespace: homework
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    # Manual sync policy - no automated section means manual sync

