apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: custom-nginx-servicemonitor
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: custom-nginx
  namespaceSelector:
    matchNames:
    - monitoring
  endpoints:
  - port: metrics
    interval: 15s
