apiVersion: v1
kind: Service
metadata:
  name: custom-nginx
  namespace: monitoring
  labels:
    app: custom-nginx
spec:
  selector:
    app: custom-nginx
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP
