apiVersion: v1
kind: Service
metadata:
  name: custom-nginx
  namespace: monitoring
  labels:
    app: custom-nginx
spec:
  selector:
    app: custom-nginx
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
  - name: metrics
    port: 9113
    targetPort: 9113
    protocol: TCP
  type: ClusterIP
