apiVersion: apps/v1
kind: Deployment
metadata:
  name: custom-nginx
  namespace: monitoring
  labels:
    app: custom-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: custom-nginx
  template:
    metadata:
      labels:
        app: custom-nginx
    spec:
      containers:
      - name: nginx
        image: custom-nginx-metrics:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 80
          name: http
