apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-config
  namespace: logging
data:
  grafana.ini: |
    [server]
    domain = localhost
    root_url = %(protocol)s://%(domain)s:%(http_port)s/
    [database]
    type = sqlite3
    [security]
    admin_user = admin
    admin_password = admin
    [analytics]
    check_for_updates = false
    [log]
    mode = console
    [grafana_net]
    url = https://grafana.net
