apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-config
  namespace: logging
data:
  loki.yaml: |
    auth_enabled: false
    server:
      http_listen_port: 3100
      grpc_listen_port: 9096
    common:
      path_prefix: /tmp/loki
      storage:
        s3:
          s3: s3://ru-central1
          endpoint: storage.yandexcloud.net
          bucketnames: loki-logs-konstsima
          access_key_id: ${ACCESS_KEY_ID}
          secret_access_key: ${ACCESS_KEY_SECRET}
          s3forcepathstyle: false
      replication_factor: 1
      ring:
        instance_addr: 127.0.0.1
        kvstore:
          store: inmemory
    schema_config:
      configs:
        - from: 2020-10-24
          store: boltdb-shipper
          object_store: s3
          schema: v11
          index:
            prefix: index_
            period: 24h
    storage_config:
      boltdb_shipper:
        active_index_directory: /tmp/loki/boltdb-shipper-active
        cache_location: /tmp/loki/boltdb-shipper-cache
        shared_store: s3
      aws:
        s3: s3://ru-central1
        endpoint: storage.yandexcloud.net
        region: ru-central1
        bucketnames: loki-logs-konstsima
        s3forcepathstyle: false
